app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {

    Route::get('/login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@getLogin']);
    Route::post('/login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@postLogin']);
    Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@logout']);

    Route::group(['namespace' => 'File'], function()
    {
        Route::get('images/{id}/resized/{size}/{crop?}',
            ['as' => 'images.resized', 'uses' => 'ImagesController@resize']
        );
        Route::resource('images', 'ImagesController', ['except' => ['destroy']]);
        Route::resource('files', 'FilesController', ['except' => ['destroy']]);
    });


    Route::get('admin', function () {
        return redirect('/admin/contents');
    });


    Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth'], function()
    {
        Route::get('contents/create/{category_id?}', ['as' => 'admin.contents.create', 'uses' => 'ContentsController@create']);
        Route::get('contents/localize/{contents}/{locale}', ['as' => 'admin.contents.localize', 'uses' => 'ContentsController@localize']);
        Route::resource('contents', 'ContentsController', ['except' => ['create']]);

        Route::get('mpoints/coords', ['as' => 'mpoints.coords', 'uses' => 'MapPointsController@coords']);
        Route::resource('mpoints', 'MapPointsController');

        Route::resource('users', 'UsersController', ['except' => ['show', 'destroy']]);

    });

    Route::get('contacts/coords', ['as' => 'contacts.coords','uses' => 'ContactsController@coords']);

    Route::group(['prefix' => '{locale?}','middleware' => ['locale']], function () {

        Route::group(['middleware' => ['tea_list']], function()
        {


            Route::get('makeup', ['as' => 'makeup', function () {
                return view('makeup.index');

            }]);


            Route::get('nistruction', ['as' => 'nistruction', function () {
                return view('makeup.nistruction');

            }]);


            Route::get('text', ['as' => 'text', function () {
                return view('makeup.text');

            }]);

            Route::get('gallery', ['as' => 'text', function () {
                return view('makeup.gallery');

            }]);


            Route::get('/', 'WelcomeController@index');

            Route::get('contacts', ['as' => 'contacts', 'uses' => 'ContactsController@index']);
            Route::get('about', ['as' => 'about', 'uses' => 'ContentsController@about']);

            Route::get('{id}', ['as' => 'contents.show','uses' => 'ContentsController@show']);
            Route::get('{id}/components', ['as' => 'contents.comps','uses' => 'ContentsController@comps']);
            Route::get('{id}/instruction', ['as' => 'contents.instruction','uses' => 'ContentsController@instruction']);
            Route::get('{id}/instruction', ['as' => 'contents.instruction','uses' => 'ContentsController@instruction']);
            Route::get('{id}/picture', ['as' => 'contents.picture','uses' => 'ContentsController@picture']);

        });
    });

});

app/MapPoint.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MapPoint extends Model
{
    protected $table = 'map_points';
    protected $guarded = [];

    public function getLatlonAttribute() {
        return [$this->lat, $this->lon];
    }

}

app/Http/Controllers/Admin/MapPointsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Http\Response;

use App\Http\Requests;

use App\Http\Controllers\Controller;

use App\MapPoint;

class MapPointsController extends Controller
{
    public function index()
    {
        $mpoints = MapPoint::get();
        return view('admin.map_points.index', [
            'mpoints' => $mpoints,
        ]);
    }

    public function coords()
    {
        $coords = [
            "type" => "FeatureCollection",
            "features" => MapPoint::get()->map(function($value, $key) {
                $balloon_content = $value->address . '<br/><a href="#" data-behavior="deleteMpoint" data-url="' . route('admin.mpoints.destroy', [$value->id]) . '">удалить</a>';

                return [
                    'type' => 'Feature',
                    "id" => $value->id,
                    "geometry" => ["type" => "Point", "coordinates" => $value->latlon],
                    "properties" => ["balloonContent" => $balloon_content, "clusterCaption" => $value->title, "hintContent" => $value->title],
                ];
            })
        ];

        return response()->json($coords);
    }


    public function create()
    {
        $mpoint = new MapPoint();

        return view('admin.map_points.new', [
            'mpoint' => $mpoint,
            'crumbs' => $this->crumbs($mpoint),
        ]);
    }

    public function store(Request $request)
    {
        $mpoint = new MapPoint($this->mpoint_params($request));

        if ( $mpoint->save() ) {
            flash()->success('Точка доавлена');
            return redirect()->route( 'admin.mpoints.index');
        }

        flash()->error('Точка не была добвлена!');
        return view('admin.map_points.new', [
            'mpoint' => $mpoint,
            'crumbs'  => $this->crumbs($mpoint)
        ]);

    }


    public function edit($id)
    {

        $mpoint = MapPoint::find($id);

        return view('admin.map_points.edit', [
            'mpoint' => $mpoint,
            'crumbs'  => $this->crumbs($mpoint)
        ]);
    }


    public function update(Request $request, $id)
    {
        $mpoint = MapPoint::find($id)
            ->fill( $this->mpoint_params($request) );

        if ( $mpoint->save() ) {
            flash()->success('Точка изменена');
            return redirect()->route( 'admin.mpoints.index');
        }

        flash()->error('Изменить тоску не удалось');
        return view('admin.map_points.edit', [
            'mpoint' => $mpoint,
            'crumbs'  => $this->crumbs($mpoint)
        ]);
    }

    public function destroy(Request $request, $id)
    {

        $point = MapPoint::find($id);
        if ( $point && $point->delete() )
        {
            return (new Response(['id' => $id], 200));
        } else {
            return (new Response(['error' => true, 'msg' => 'Bad request'], 403));
        }

    }


    private function mpoint_params($request)
    {
        return $request->mpoint ?: [];
    }


    private function crumbs($mpoint)
    {
        $crumbs = [['title' => 'Точки на карте', 'url' => route('admin.mpoints.index')]];

        if ( $mpoint->exists ) {
            $crumb = ['title' => "Редактривание точки", 'active' => true];
        } else {
            $crumb = ['title' => "Добавление точки", 'active' => true];
        }

        array_push($crumbs, $crumb);

        return collect($crumbs);
    }
}

resources/views/admin/map_points/edit.blade.php
@extends('layouts.admin')

@section('content')

    @can('everything')
        @include('admin.partials.breadcrumbs', ['crumbs' => $crumbs])
    @endcan

    <div class="page-header">
        <h1>{!! $crumbs->last()['title'] !!}</h1>
    </div>

    @include('admin.map_points.form')
@stop

resources/views/admin/map_points/form.blade.php
<div class="row">

    {!! Form::resource($mpoint, ['route' => 'admin.mpoints', 'class' => 'form-horizontal']) !!}

        <div class="tab-content">

            @include('admin.partials.errors', ['errors' => $mpoint->errors])

        </div>


        <div class="row top-buffer">

            <div class="form-group">
                {!! Form::label('mpoint[title]', 'Заголовок', ['class' => 'control-label col-sm-2'])  !!}
                <div class="col-sm-8">
                    {!! Form::text('mpoint[title]', $mpoint->title, array('class' => 'form-control')) !!}
                </div>
            </div>

            <div class="form-group">
                {!! Form::label('mpoint[address]', 'Адрес', ['class' => 'control-label col-sm-2'])  !!}
                <div class="col-sm-8">
                    {!! Form::textarea('mpoint[address]', $mpoint->address, array('class' => 'form-control', 'rows' => 2)) !!}
                </div>
            </div>

            <div class="form-group">
                {!! Form::label('mpoint[desc]', 'Описание', ['class' => 'control-label col-sm-2'])  !!}
                <div class="col-sm-8">
                    {!! Form::textarea('mpoint[desc]', $mpoint->desc, array('class' => 'form-control', 'rows' => 3)) !!}
                </div>
            </div>

            <div class="form-group">
                {!! Form::label('point', 'Точка на карте', ['class' => 'control-label col-sm-2'])  !!}
                <div class="col-sm-8">
                    {!! Form::hidden('mpoint[lat]', $mpoint->lat) !!}
                    {!! Form::hidden('mpoint[lon]', $mpoint->lon) !!}
                    <div id="touchable-map" style="height:400px"></div>
                </div>
            </div>
        </div>


        @include("admin.partials.form._button_bar", ['object' => $mpoint, 'lifecycled' => true])


    {!! Form::close() !!}

</div>

resources/views/admin/map_points/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="row">

        <h1>
            Точки на карте
            {!! link_to_route('admin.mpoints.create', 'Добавить', [], ['class' => 'btn btn-primary']) !!}
        </h1>

        <ul class="nav nav-pills">
            <li class="active"><a data-toggle="tab" href="#map">Карта</a></li>
            <li class=""><a data-toggle="tab" href="#points">Точки</a></li>
        </ul>

        <div class="tab-content">

            <div id="map" class="tab-pane fade in active">
                <div id="preview-map" style="height:600px" ></div>
            </div>


            <div id="points" class="tab-pane top-buffer">

                @if ($mpoints->isEmpty())
                    <p>Нет ни одной точки</p>

                @else
                    <table class="table table-hover">
                        <colgroup>
                            <col width="70%"/>
                        </colgroup>
                        <thead>
                        <tr>
                            <th>Заголовок</th>
                            {{--<th>Тип</th>--}}
                        </tr>
                        </thead>
                        <tbody>

                        @foreach ($mpoints as $mpoint)
                            <tr>

                                <td> {!! link_to_route('admin.mpoints.edit', $mpoint->title, [$mpoint->id]) !!} </td>

                            </tr>

                        @endforeach

                        </tbody>
                    </table>

                @endif

            </div>
        </div>
    </div>
@stop

resources/views/admin/map_points/new.blade.php
@extends('layouts.admin')

@section('content')

    @can('everything')
        @include('admin.partials.breadcrumbs', ['crumbs' => $crumbs])
    @endcan

    <div class="page-header">
        <h1>{!! $crumbs->last()['title'] !!} </h1>
    </div>

    @include('admin.map_points.form')
@stop