app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {

    Route::get('/login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@getLogin']);
    Route::post('/login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@postLogin']);
    Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@logout']);

    Route::group(['namespace' => 'File'], function()
    {
        Route::get('images/{id}/resized/{size}/{crop?}',
            ['as' => 'images.resized', 'uses' => 'ImagesController@resize']
        );
        Route::resource('images', 'ImagesController', ['except' => ['destroy']]);
        Route::resource('files', 'FilesController', ['except' => ['destroy']]);
    });


    Route::get('admin', function () {
        return redirect('/admin/contents');
    });


    Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth'], function()
    {
        Route::get('contents/create/{category_id?}', ['as' => 'admin.contents.create', 'uses' => 'ContentsController@create']);
        Route::get('contents/localize/{contents}/{locale}', ['as' => 'admin.contents.localize', 'uses' => 'ContentsController@localize']);
        Route::resource('contents', 'ContentsController', ['except' => ['create']]);

        Route::get('mpoints/coords', ['as' => 'mpoints.coords', 'uses' => 'MapPointsController@coords']);
        Route::resource('mpoints', 'MapPointsController');

        Route::resource('users', 'UsersController', ['except' => ['show', 'destroy']]);

    });

    Route::get('contacts/coords', ['as' => 'contacts.coords','uses' => 'ContactsController@coords']);

    Route::group(['prefix' => '{locale?}','middleware' => ['locale']], function () {

        Route::group(['middleware' => ['tea_list']], function()
        {


            Route::get('makeup', ['as' => 'makeup', function () {
                return view('makeup.index');

            }]);


            Route::get('nistruction', ['as' => 'nistruction', function () {
                return view('makeup.nistruction');

            }]);


            Route::get('text', ['as' => 'text', function () {
                return view('makeup.text');

            }]);

            Route::get('gallery', ['as' => 'text', function () {
                return view('makeup.gallery');

            }]);


            Route::get('/', 'WelcomeController@index');

            Route::get('contacts', ['as' => 'contacts', 'uses' => 'ContactsController@index']);
            Route::get('about', ['as' => 'about', 'uses' => 'ContentsController@about']);

            Route::get('{id}', ['as' => 'contents.show','uses' => 'ContentsController@show']);
            Route::get('{id}/components', ['as' => 'contents.comps','uses' => 'ContentsController@comps']);
            Route::get('{id}/instruction', ['as' => 'contents.instruction','uses' => 'ContentsController@instruction']);
            Route::get('{id}/instruction', ['as' => 'contents.instruction','uses' => 'ContentsController@instruction']);
            Route::get('{id}/picture', ['as' => 'contents.picture','uses' => 'ContentsController@picture']);

        });
    });

});

resources/views/admin/partials/breadcrumbs.blade.php
<ol class="breadcrumb">
    @foreach ($crumbs as $crumb)
        @if ( isset($crumb['active']) && $crumb['active'] )
            <li class="active">{!! $crumb['title'] !!}</li>
        @else
            <li>{!! link_to($crumb['url'], $crumb['title']) !!}</li>
        @endif
    @endforeach
</ol>

resources/views/admin/partials/errors.blade.php
@if (count($errors) > 0)
    <div class="alert alert-warning">
        Что-то <strong>не так</strong>
        с данными в вашей форме!<br><br>
        <ul>
            @foreach ($errors as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/admin/partials/lifecycle_menu.blade.php
<div class="btn-group">

    <?php
    $state_menu = [
            'live' => 'Живые',
            'archive' => 'Архивные'
    ];

    $active_state = $state ? $state : 'live';
    ?>

    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {!! $state_menu[$active_state] !!} <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        @foreach($state_menu as $state => $state_title)
            <li>{!! link_to_route($route, $state_title, ['state' => $state ], []) !!}</li>
        @endforeach
    </ul>
</div>

resources/views/admin/partials/navbar.blade.php
<?php

$menu = [

    'ContentsController1'  => [
        'title' => 'Контент',

        'subs' => [
            '1' => [
                    'title' => 'Главная',
                    'url'   => route('admin.contents.edit', ['id' => 1]),
            ],
            '2' => [
                    'title' => 'О компании (Виктория)',
                    'url'   => route('admin.contents.edit', ['id' => 2]),
            ],
            '3' => [
                    'title' => 'О компании (Галина)',
                    'url'   => route('admin.contents.edit', ['id' => 12]),
            ],
            '4' => [
                    'title' => 'О заводе',
                    'url'   => route('admin.contents.edit', ['id' => 3]),
            ],
        ]
    ],

    'ContentsController2'  => [
        'title' => 'Чаи',

        'subs' => [
            '4' => [
                    'title' => 'Nomad',
                    'url'   => route('admin.contents.edit', ['id' => 4]),
            ],
            '5' => [
                    'title' => 'Hammam',
                    'url'   => route('admin.contents.edit', ['id' => 5]),
            ],
            '6' => [
                    'title' => 'Yoga',
                    'url'   => route('admin.contents.edit', ['id' => 6]),
            ],
        ]
    ],


    'ContentsController3'  => [
        'title' => 'Точки на карте',
        'url' => route('admin.mpoints.index'),
    ],


    /*'dropdown'  => [
        'title' => 'Настройки',
        'subs' => [
            'ContentsController' => [
                'title' => 'Калькулятор',
                'url'   => route('admin.contents.index'),
            ],
            'ContentsController' => [
                'title' => 'Меню',
                'url'   => route('admin.contents.index'),
            ],
        ]
    ],*/
];

foreach ($menu as $item => $options)
{
    if ( isset( $options['subs'] ) )
    {
        $active[$item] = $item;

        foreach ($options['subs'] as $subitem => $options)
        {
            if ( $subitem == $controller )
            {
                $active[$subitem] = 'active';
                $active[$item] = 'active';
            } else {
                $active[$subitem] = '';
            }
        }

    } else {
        $active[$item] = $item == $controller ? 'active' : '';
    }
}

$active[$controller] = isset($active[$controller]) ? $active[$controller] : '';

//var_dump($active);

?>

<ul class="nav navbar-nav">


    @if (Auth::check())

        @foreach ($menu as $item => $options)

            <li class="{{ $active[$item] }}">

                @if ( isset( $options['subs'] ) )

                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        {{ $options['title'] }}  <span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu">
                        @foreach ($options['subs'] as $subitem => $options)

                            <li class="{{ $active[$subitem] }}">
                                <a href="{{ $options['url'] }}">
                                    {{ $options['title'] }}
                                </a>
                            </li>

                        @endforeach
                    </ul>

                @else
                    <a href={{ $options['url'] }}>
                        {{ $options['title'] }}

                        @if (isset($options['badge']) && $options['badge'])
                            <span class="badge">{!! $options['badge'] !!}</span>
                        @endif
                    </a>
                @endif
            </li>

        @endforeach
    @endif
</ul>

<ul class="nav navbar-nav navbar-right">
    @if (Auth::guest())
        <li>{!! link_to_route('auth.login', 'Войти') !!}</li>
    @else
        <li>{!! link_to_route('admin.users.index', 'Пользователи') !!}</li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
               aria-expanded="false">{{ Auth::user()->name }}
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li>{!! link_to_route('auth.logout', 'Выйти') !!}</li>
            </ul>
        </li>
    @endif
</ul>